language: python

sudo: required

services:
  - docker

python:
  - 3.8

cache: pip

before_install:
  - docker run -d -p 9200:9200
    -e http.host=0.0.0.0
    -e transport.host=127.0.0.1
    -e xpack.security.enabled=false
    -e xpack.monitoring.enabled=false
    docker.elastic.co/elasticsearch/elasticsearch:7.8.0

install:
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --system --deploy
  - pip install --upgrade pip codecov
  - pip install -e .[test]

script:
  - pytest --cov=image_match && codecov
