version: '2'

services:

  image-match:
    build: 
      context: .
    image: ascribe/image-match
    container_name: image-match
    volumes:
      - .:/usr/src/app/
    depends_on:
     - "elasticsearch"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
